/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author cindy
 */
public class MetodoSimplex extends javax.swing.JPanel {

    /**
     * Creates new form SimplexMaxi
     */
    public MetodoSimplex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEX1 = new javax.swing.JTextField();
        txtEX2 = new javax.swing.JTextField();
        txtX3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRX1 = new javax.swing.JTextField();
        txtRX2 = new javax.swing.JTextField();
        txtRY1 = new javax.swing.JTextField();
        txtRY2 = new javax.swing.JTextField();
        txtRS3 = new javax.swing.JTextField();
        txtRS1 = new javax.swing.JTextField();
        txtRS2 = new javax.swing.JTextField();
        txtRZ3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRZ1 = new javax.swing.JTextField();
        txtRZ2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jpanelmtd_simplex = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(230, 230, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEX1ActionPerformed(evt);
            }
        });
        add(txtEX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 50, -1));
        add(txtEX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 60, -1));
        add(txtX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 50, -1));

        jLabel3.setText("X1");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel4.setText("X2");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel5.setText("X3");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));
        add(txtRX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 40, -1));
        add(txtRX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 40, -1));

        txtRY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRY1ActionPerformed(evt);
            }
        });
        add(txtRY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 50, -1));
        add(txtRY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 50, -1));

        txtRS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRS3ActionPerformed(evt);
            }
        });
        add(txtRS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 50, -1));

        txtRS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRS1ActionPerformed(evt);
            }
        });
        add(txtRS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 50, -1));

        txtRS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRS2ActionPerformed(evt);
            }
        });
        add(txtRS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 50, -1));

        txtRZ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRZ3ActionPerformed(evt);
            }
        });
        add(txtRZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 50, 20));

        jLabel7.setText("X");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 10, -1));

        jLabel8.setText("X");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        jLabel9.setText("+");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 20, -1));

        jLabel10.setText("Y");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 10, -1));

        jLabel11.setText("Y");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 20, -1));

        jLabel12.setText("X, Y");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, -1, -1));

        jLabel13.setText("+");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));
        add(txtRZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 50, -1));
        add(txtRZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 50, -1));

        jLabel14.setText("+");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 20, -1));

        jLabel15.setText("+");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 20, -1));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(33, 48, 71));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 130, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 130, -1));

        jSeparator1.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator1.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 980, 2));

        jSeparator3.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator3.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator3.setOpaque(true);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, -7, 2, 700));

        jSeparator2.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator2.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator2.setOpaque(true);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 663, 980, 2));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 48, 71));
        jLabel17.setText("MÉTODO SIMPLEX");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 25));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 48, 71));
        jLabel1.setText("Ecuación:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(33, 48, 71));
        jLabel18.setText("Restricciones");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, -1, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(33, 48, 71));
        jLabel19.setText("RESPUESTA");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        btnMinimizar.setBackground(new java.awt.Color(204, 204, 204));
        btnMinimizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(33, 48, 71));
        btnMinimizar.setText("MINIMIZAR");
        btnMinimizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 100, 30));

        btnMaximizar.setBackground(new java.awt.Color(204, 204, 204));
        btnMaximizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnMaximizar.setForeground(new java.awt.Color(33, 48, 71));
        btnMaximizar.setText("MAXIMIZAR");
        btnMaximizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximizarActionPerformed(evt);
            }
        });
        add(btnMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 100, 30));

        txtTipo.setBackground(new java.awt.Color(230, 230, 230));
        txtTipo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(33, 48, 71));
        txtTipo.setBorder(null);
        add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 130, 25));
        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));
        add(jpanelmtd_simplex, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 850, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEX1ActionPerformed

    private void txtRS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRS3ActionPerformed

    private void txtRS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRS2ActionPerformed

    private void txtRY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRY1ActionPerformed

    private void txtRS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRS1ActionPerformed

    private void txtRZ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRZ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRZ3ActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        txtTipo.setText(" - MINIMIZAR");
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnMaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximizarActionPerformed
        txtTipo.setText(" - MAXIMIZAR");
    }//GEN-LAST:event_btnMaximizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JScrollPane jpanelmtd_simplex;
    private javax.swing.JTextField txtEX1;
    private javax.swing.JTextField txtEX2;
    private javax.swing.JTextField txtRS1;
    private javax.swing.JTextField txtRS2;
    private javax.swing.JTextField txtRS3;
    private javax.swing.JTextField txtRX1;
    private javax.swing.JTextField txtRX2;
    private javax.swing.JTextField txtRY1;
    private javax.swing.JTextField txtRY2;
    private javax.swing.JTextField txtRZ1;
    private javax.swing.JTextField txtRZ2;
    private javax.swing.JTextField txtRZ3;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtX3;
    // End of variables declaration//GEN-END:variables
}
