/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author cindy
 */
public class ModeloAsignacion extends javax.swing.JPanel {
    private double[][] matriz;              // matriz en proceso (reducida)
    private double[][] original;            // matriz original (costos reales)
    private Set<Integer> filasMarcadas = new HashSet<>();     // filas "marcadas" durante trazo
    private Set<Integer> columnasMarcadas = new HashSet<>();  // columnas "marcadas"
    private int[] asignacionFinal = null;   // asignacion final: indiceCol para cada fila (o -1)

    private double[][] valoresOriginales;
    private java.util.List<Integer> columnasColoreadas = new ArrayList<>();
    private java.util.List<Integer> filasColoreadas = new ArrayList<>();
    private int contadorAsignaciones = 0;

    public ModeloAsignacion() {
        initComponents();
         
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        txtTipo1 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtColumnas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnTablas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setBackground(new java.awt.Color(230, 230, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator1.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 980, 2));

        jSeparator3.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator3.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator3.setOpaque(true);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, -7, 2, 700));

        jSeparator2.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator2.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator2.setOpaque(true);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 663, 980, 2));

        jLabel7.setBackground(new java.awt.Color(230, 230, 230));
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 485, 150, 40));

        jLabel6.setBackground(new java.awt.Color(230, 230, 230));
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 520, 30, 160));

        jLabel5.setBackground(new java.awt.Color(230, 230, 230));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 30, 160));

        jLabel3.setBackground(new java.awt.Color(230, 230, 230));
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 650, 150, 40));

        jTextPane1.setBackground(new java.awt.Color(230, 230, 230));
        jTextPane1.setText("⠐⣪⡑⣤⣶⣶⣶⣦⡔⣩⡒⠀ ⢸⣯⣾⣿⢏⣿⣏⢿⣿⣮⣿⠀ ⢸⣿⢸⡗⣶⠙⢱⡖⣿⢸⣿⠀ ⢸⡿⠀⠳⣄⣐⣂⡴⠃⠸⣿⠀ ⣾⠃⠀⡵⡔⠕⠕⡰⡅⠀⢻⡆ ⢹⡆⠘⢴⠙⠑⠉⢳⡱⠀⣾⠁ ⠊⠀⠀⠈⡖⡖⡖⡎⠀⠀⠈⠂ ⠀⠀⠀⠀⠉⠁⠉⠁⠀⠀⠀⠀");
        jTextPane1.setToolTipText("");
        jScrollPane2.setViewportView(jTextPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 130, 140));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 48, 71));
        jLabel2.setText("MODELO de ASIGNACIÓN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, -1, 30));

        txtTipo1.setBackground(new java.awt.Color(230, 230, 230));
        txtTipo1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtTipo1.setForeground(new java.awt.Color(33, 48, 71));
        txtTipo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTipo1.setBorder(null);
        txtTipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipo1ActionPerformed(evt);
            }
        });
        add(txtTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 370, 25));

        btnCalcular.setBackground(new java.awt.Color(204, 204, 204));
        btnCalcular.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(33, 48, 71));
        btnCalcular.setText("CALCULAR");
        btnCalcular.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 100, 30));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 48, 71));
        jLabel17.setText("Columnas:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 150, 120, 30));

        txtColumnas.setBackground(new java.awt.Color(204, 204, 204));
        txtColumnas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtColumnas.setForeground(new java.awt.Color(33, 48, 71));
        txtColumnas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtColumnas.setBorder(null);
        txtColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColumnasActionPerformed(evt);
            }
        });
        add(txtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 155, 120, 25));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 48, 71));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Resultados");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 100, -1));

        txtResultados.setColumns(20);
        txtResultados.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txtResultados.setRows(5);
        jScrollPane3.setViewportView(txtResultados);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 340, 210));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(33, 48, 71));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 100, 30));

        btnTablas.setBackground(new java.awt.Color(204, 204, 204));
        btnTablas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnTablas.setForeground(new java.awt.Color(33, 48, 71));
        btnTablas.setText("PLAY");
        btnTablas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnTablas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablasActionPerformed(evt);
            }
        });
        add(btnTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, 30));

        tblDatos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        tblDatos.setForeground(new java.awt.Color(33, 48, 71));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 730, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipo1ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

                                         
    try {
        filasMarcadas.clear();
        columnasMarcadas.clear();
        asignacionFinal = null;
        matriz = null;
        original = null;

        DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
        int filas = modelo.getRowCount();
        int columnasTot = modelo.getColumnCount();

        if (columnasTot <= 1 || filas == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos para procesar.");
            return;
        }

        int columnas = columnasTot - 1; 
        matriz = new double[filas][columnas];
        original = new double[filas][columnas];

        // Cargar matriz
        for (int i = 0; i < filas; i++) {
            for (int j = 1; j <= columnas; j++) {
                double val = getValorNumerico(modelo.getValueAt(i, j));
                matriz[i][j - 1] = val;
                original[i][j - 1] = val;
            }
        }

        // Resta mínima por filas
        for (int i = 0; i < filas; i++) {
            double min = Arrays.stream(matriz[i]).min().orElse(0);
            for (int j = 0; j < columnas; j++) matriz[i][j] -= min;
        }

        // Resta mínima por columnas
        for (int j = 0; j < columnas; j++) {
            double min = Double.MAX_VALUE;
            for (int i = 0; i < filas; i++) min = Math.min(min, matriz[i][j]);
            if (min == Double.MAX_VALUE) min = 0;
            for (int i = 0; i < filas; i++) matriz[i][j] -= min;
        }

        // Mostrar matriz reducida
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                modelo.setValueAt(String.format("%.2f", matriz[i][j]), i, j + 1);
            }
        }

        // --- Intentar encontrar asignación ---
        int[] match = findMaximumMatchingZeros(matriz);
        int iteraciones = 0;
        int maxIter = 20; // 🔹 límite para evitar bucles infinitos

        while (countAssigned(match) < filas && iteraciones < maxIter) {
            iteraciones++;

            Map<Integer, Integer> asignaciones = new HashMap<>();
            for (int i = 0; i < match.length; i++)
                if (match[i] != -1) asignaciones.put(i, match[i]);

            trazarLineas(asignaciones);
            ajustarMatriz();

            // Actualizar tabla
            for (int i = 0; i < filas; i++)
                for (int j = 0; j < columnas; j++)
                    modelo.setValueAt(String.format("%.2f", matriz[i][j]), i, j + 1);

            match = findMaximumMatchingZeros(matriz);
        }

        if (iteraciones >= maxIter) {
            JOptionPane.showMessageDialog(this, 
                "El algoritmo no pudo encontrar una asignación óptima.\n" +
                "Verifique los valores de la matriz.", 
                "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        asignacionFinal = match.clone();
        colorearTabla();
        mostrarResultados(asignacionFinal, original);
        tblDatos.repaint();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al procesar los datos: " + e.getMessage());
        e.printStackTrace();
    }



    
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColumnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColumnasActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
           txtResultados.setText("");
    asignacionFinal = null;
    filasMarcadas.clear();
    columnasMarcadas.clear();
    matriz = null;
    original = null;

    DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
    for (int i = 0; i < modelo.getRowCount(); i++) {
        for (int j = 1; j < modelo.getColumnCount(); j++) {
            modelo.setValueAt("", i, j);
        }
    }

    tblDatos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer());
    tblDatos.repaint();


    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablasActionPerformed
        try {
            int n = Integer.parseInt(txtColumnas.getText().trim());

            if (n <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese un número mayor que 0.");
                return;
            }

            // Crear encabezados 
            String[] columnas = new String[n + 1];
            columnas[0] = " ";
            for (int i = 1; i <= n; i++) {
                columnas[i] = String.valueOf((char) ('A' + (i - 1)));
            }

            // Crear datos 
            Object[][] datos = new Object[n][n + 1];
            for (int fila = 0; fila < n; fila++) {
                datos[fila][0] = fila + 1;
                for (int col = 1; col <= n; col++) {
                    datos[fila][col] = "";
                }
            }

            DefaultTableModel modelo = new DefaultTableModel(datos, columnas);
            tblDatos.setModel(modelo);

            JTableHeader header = tblDatos.getTableHeader();
            ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            for (int i = 0; i < tblDatos.getColumnCount(); i++) {
                tblDatos.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

            // limpieza de marcados previos si hubiese
            filasMarcadas.clear();
            columnasMarcadas.clear();
            asignacionFinal = null;

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido en columnas");
        }
    }

    // ========================= MÉTODOS AUXILIARES =========================

    /**
     * Convierte un object a double. Acepta tanto "1.23" como "1,23". Si es vacío o inválido devuelve 0.
     */
    private double getValorNumerico(Object o) {
        if (o == null) return 0;
        try {
            String s = o.toString().trim();
            if (s.isEmpty()) return 0;
            // permitir coma decimal
            s = s.replace(",", ".");
            return Double.parseDouble(s);
        } catch (Exception ex) {
            return 0;
        }
    }

    /**
     * Cuenta cuántas filas tienen asignación (match[row] != -1).
     */
    private int countAssigned(int[] match) {
        int c = 0;
        for (int v : match) if (v != -1) c++;
        return c;
    }

    /**
     * Encuentra un emparejamiento máximo en el grafo bipartito filas->columnas donde hay arista si matriz[i][j]==0.
     * Usa algoritmo tipo Kuhn (DFS augmenting paths).
     * Retorna array matchRowToCol[row] = col o -1 si no asignado.
     */
    private int[] findMaximumMatchingZeros(double[][] mat) {
        int n = mat.length;
        int m = mat[0].length;
        int[] matchColToRow = new int[m];
        Arrays.fill(matchColToRow, -1);

        for (int v = 0; v < n; v++) {
            boolean[] seen = new boolean[m];
            dfsMatch(v, mat, matchColToRow, seen);
        }

        int[] matchRowToCol = new int[n];
        Arrays.fill(matchRowToCol, -1);
        for (int j = 0; j < m; j++) {
            if (matchColToRow[j] != -1) {
                matchRowToCol[matchColToRow[j]] = j;
            }
        }
        return matchRowToCol;
    }

    private boolean dfsMatch(int v, double[][] mat, int[] matchColToRow, boolean[] seen) {
        int m = mat[0].length;
        for (int j = 0; j < m; j++) {
            if (Math.abs(mat[v][j]) < 1e-9 && !seen[j]) {
                seen[j] = true;
                if (matchColToRow[j] == -1 || dfsMatch(matchColToRow[j], mat, matchColToRow, seen)) {
                    matchColToRow[j] = v;
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Traza las filas y columnas marcadas según el procedimiento estándar:
     * - Marcar todas las filas que NO están asignadas.
     * - Repetir: marcar columnas que tienen ceros en filas marcadas, y marcar filas que tienen asignación en columnas marcadas.
     * El resultado queda en filasMarcadas y columnasMarcadas (sets).
     */
    private void trazarLineas(Map<Integer, Integer> asignaciones) {
        filasMarcadas.clear();
        columnasMarcadas.clear();

        // filas sin asignar
        for (int i = 0; i < matriz.length; i++) {
            if (!asignaciones.containsKey(i)) filasMarcadas.add(i);
        }

        boolean cambio = true;
        while (cambio) {
            cambio = false;
            // por cada fila marcada, marcar columnas que tengo ceros
            for (int fila : new HashSet<>(filasMarcadas)) {
                for (int j = 0; j < matriz[0].length; j++) {
                    if (Math.abs(matriz[fila][j]) < 1e-9 && !columnasMarcadas.contains(j)) {
                        columnasMarcadas.add(j);
                        cambio = true;
                    }
                }
            }
            // por cada columna marcada, marcar filas que tengan asignacion en esa columna
            for (Map.Entry<Integer, Integer> e : asignaciones.entrySet()) {
                int filaAsignada = e.getKey();
                int colAsignada = e.getValue();
                if (columnasMarcadas.contains(colAsignada) && !filasMarcadas.contains(filaAsignada)) {
                    filasMarcadas.add(filaAsignada);
                    cambio = true;
                }
            }
        }
        // las líneas cubrirán: todas las filas NO marcadas (complemento) y todas las columnas marcadas.
        // La información de las filas/columnas marcadas se usa en colorearTabla() para pintar el trazado.
    }

    /**
     * Ajusta la matriz según el mínimo no cubierto:
     * - encontrar min no cubierto (filas NO marcadas y columnas NO marcadas),
     * - restarlo a todos no cubiertos,
     * - sumarlo en las intersecciones de filas marcadas y columnas marcadas.
     */
    private void ajustarMatriz() {
        double minNoCubierto = Double.MAX_VALUE;
        int filas = matriz.length;
        int cols = matriz[0].length;
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < cols; j++) {
                boolean filaMarc = filasMarcadas.contains(i);
                boolean colMarc = columnasMarcadas.contains(j);
                // No cubierto => fila NO marcada y columna NO marcada
                if (!filaMarc && !colMarc) {
                    minNoCubierto = Math.min(minNoCubierto, matriz[i][j]);
                }
            }
        }
        if (minNoCubierto == Double.MAX_VALUE) minNoCubierto = 0;

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < cols; j++) {
                boolean filaMarc = filasMarcadas.contains(i);
                boolean colMarc = columnasMarcadas.contains(j);
                if (!filaMarc && !colMarc) {
                    matriz[i][j] -= minNoCubierto;
                } else if (filaMarc && colMarc) {
                    matriz[i][j] += minNoCubierto;
                }
            }
        }
    }

    /**
     * Colorea la tabla mostrando:
     * - celdas cubiertas por líneas: filas NO marcadas (línea horizontal) o columnas marcadas (línea vertical)
     * - intersección (ambas) en amarillo
     * - asignaciones finales (si existen) en verde.
     *
     * Nota: la columna 0 (numeración de filas) no se colorea.
     */
    private void colorearTabla() {
        tblDatos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // default background
                c.setBackground(Color.WHITE);

                // si no hay matriz aún, centrar y devolver blanco
                if (matriz == null) {
                    setHorizontalAlignment(SwingConstants.CENTER);
                    return c;
                }

                // la columna 0 es la numeración: no la tocamos en color
                if (column == 0) {
                    setHorizontalAlignment(SwingConstants.CENTER);
                    return c;
                }

                int colMatriz = column - 1;
                boolean filaMarcada = filasMarcadas.contains(row);
                boolean colMarcada = columnasMarcadas.contains(colMatriz);

                // las líneas se dibujan en: filas NO marcadas (horizontal) y columnas marcadas (vertical)
                boolean filaCubiertaPorLinea = !filaMarcada;
                boolean colCubiertaPorLinea = colMarcada;
                boolean cubierta = filaCubiertaPorLinea || colCubiertaPorLinea;

                // si hay asignación final, pintarla (verde)
                if (asignacionFinal != null && asignacionFinal.length > row && asignacionFinal[row] == colMatriz) {
                    c.setBackground(new Color(170, 255, 180)); // verde suave para asignaciones finales
                } else if (filaCubiertaPorLinea && colCubiertaPorLinea) {
                    c.setBackground(new Color(255, 255, 150)); // intersección: amarillo
                } else if (filaCubiertaPorLinea) {
                    c.setBackground(new Color(200, 230, 255)); // fila cubierta (horizontal)
                } else if (colCubiertaPorLinea) {
                    c.setBackground(new Color(255, 220, 220)); // columna cubierta (vertical)
                } else {
                    // si no está cubierta, mantener fondo blanco
                    c.setBackground(Color.WHITE);
                }

                // Centrar texto
                setHorizontalAlignment(SwingConstants.CENTER);
                return c;
            }
        });
    }

    /**
     * Muestra en txtResultados el resultado final usando la matriz original de costos.
     * asignacion[row] = col (índice 0..n-1)
     */
    private void mostrarResultados(int[] asignacion, double[][] originalMat) {
        if (asignacion == null) {
            txtResultados.setText("No hay asignación final.");
            return;
        }
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < asignacion.length; i++) {
            int col = asignacion[i];
            if (col >= 0) {
                double costo = originalMat[i][col];
                String nombreCol = String.valueOf((char) ('A' + col));
                sb.append("R").append(i + 1).append(" - ").append(nombreCol)
                        .append(" - ").append(String.format("%.2f", costo)).append("\n");
            } else {
                sb.append("R").append(i + 1).append(" - sin asignar\n");
            }
        }
        txtResultados.setText(sb.toString());
    }//GEN-LAST:event_btnTablasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnTablas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    public javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtColumnas;
    public javax.swing.JTextArea txtResultados;
    private javax.swing.JTextField txtTipo1;
    // End of variables declaration//GEN-END:variables
}
