/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author cindy
 */
public class ModeloAsignacion extends javax.swing.JPanel {
    private double[][] matriz;              // matriz en proceso (reducida)
    private double[][] original;            // matriz original (costos reales)
    private Set<Integer> filasMarcadas = new HashSet<>();     // filas "marcadas" durante trazo
    private Set<Integer> columnasMarcadas = new HashSet<>();  // columnas "marcadas"
    private int[] asignacionFinal = null;   // asignacion final: indiceCol para cada fila (o -1)

    private double[][] valoresOriginales;
    private java.util.List<Integer> columnasColoreadas = new ArrayList<>();
    private java.util.List<Integer> filasColoreadas = new ArrayList<>();
    private int contadorAsignaciones = 0;

    public ModeloAsignacion() {
        initComponents();
         // 🔹 Renderizador que colorea los ceros en rojo
    
    }
private int[] hungarianAlgorithm(double[][] costMatrix) {
    int n = costMatrix.length;
    int m = costMatrix[0].length;
    int dim = Math.max(n, m);

    double[][] cost = new double[dim][dim];
    for (int i = 0; i < dim; i++) {
        for (int j = 0; j < dim; j++) {
            if (i < n && j < m)
                cost[i][j] = costMatrix[i][j];
            else
                cost[i][j] = 0;
        }
    }

    double[] u = new double[dim + 1];
    double[] v = new double[dim + 1];
    int[] p = new int[dim + 1];
    int[] way = new int[dim + 1];

    for (int i = 1; i <= dim; i++) {
        p[0] = i;
        int j0 = 0;
        double[] minv = new double[dim + 1];
        boolean[] used = new boolean[dim + 1];
        Arrays.fill(minv, Double.POSITIVE_INFINITY);
        Arrays.fill(used, false);
        do {
            used[j0] = true;
            int i0 = p[j0], j1 = 0;
            double delta = Double.POSITIVE_INFINITY;
            for (int j = 1; j <= dim; j++) {
                if (!used[j]) {
                    double cur = cost[i0 - 1][j - 1] - u[i0] - v[j];
                    if (cur < minv[j]) {
                        minv[j] = cur;
                        way[j] = j0;
                    }
                    if (minv[j] < delta) {
                        delta = minv[j];
                        j1 = j;
                    }
                }
            }
            for (int j = 0; j <= dim; j++) {
                if (used[j]) {
                    u[p[j]] += delta;
                    v[j] -= delta;
                } else {
                    minv[j] -= delta;
                }
            }
            j0 = j1;
        } while (p[j0] != 0);

        do {
            int j1 = way[j0];
            p[j0] = p[j1];
            j0 = j1;
        } while (j0 != 0);
    }

    int[] ans = new int[n];
    for (int j = 1; j <= dim; j++) {
        if (p[j] <= n && j <= m) {
            ans[p[j] - 1] = j - 1;
        }
    }
    return ans;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        txtTipo1 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtColumnas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnTablas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setBackground(new java.awt.Color(230, 230, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator1.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 980, 2));

        jSeparator3.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator3.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator3.setOpaque(true);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, -7, 2, 700));

        jSeparator2.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator2.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator2.setOpaque(true);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 663, 980, 2));

        jLabel7.setBackground(new java.awt.Color(230, 230, 230));
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 485, 150, 40));

        jLabel6.setBackground(new java.awt.Color(230, 230, 230));
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 520, 30, 160));

        jLabel5.setBackground(new java.awt.Color(230, 230, 230));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 30, 160));

        jLabel3.setBackground(new java.awt.Color(230, 230, 230));
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 650, 150, 40));

        jTextPane1.setBackground(new java.awt.Color(230, 230, 230));
        jTextPane1.setText("⠐⣪⡑⣤⣶⣶⣶⣦⡔⣩⡒⠀ ⢸⣯⣾⣿⢏⣿⣏⢿⣿⣮⣿⠀ ⢸⣿⢸⡗⣶⠙⢱⡖⣿⢸⣿⠀ ⢸⡿⠀⠳⣄⣐⣂⡴⠃⠸⣿⠀ ⣾⠃⠀⡵⡔⠕⠕⡰⡅⠀⢻⡆ ⢹⡆⠘⢴⠙⠑⠉⢳⡱⠀⣾⠁ ⠊⠀⠀⠈⡖⡖⡖⡎⠀⠀⠈⠂ ⠀⠀⠀⠀⠉⠁⠉⠁⠀⠀⠀⠀");
        jTextPane1.setToolTipText("");
        jScrollPane2.setViewportView(jTextPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 130, 140));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 48, 71));
        jLabel2.setText("MODELO de ASIGNACIÓN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, -1, 30));

        txtTipo1.setBackground(new java.awt.Color(230, 230, 230));
        txtTipo1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtTipo1.setForeground(new java.awt.Color(33, 48, 71));
        txtTipo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTipo1.setBorder(null);
        txtTipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipo1ActionPerformed(evt);
            }
        });
        add(txtTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 370, 25));

        btnCalcular.setBackground(new java.awt.Color(204, 204, 204));
        btnCalcular.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(33, 48, 71));
        btnCalcular.setText("CALCULAR");
        btnCalcular.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 100, 30));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 48, 71));
        jLabel17.setText("Columnas:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 150, 120, 30));

        txtColumnas.setBackground(new java.awt.Color(204, 204, 204));
        txtColumnas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtColumnas.setForeground(new java.awt.Color(33, 48, 71));
        txtColumnas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtColumnas.setBorder(null);
        txtColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColumnasActionPerformed(evt);
            }
        });
        add(txtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 155, 120, 25));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 48, 71));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Resultados");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 100, -1));

        txtResultados.setColumns(20);
        txtResultados.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txtResultados.setRows(5);
        jScrollPane3.setViewportView(txtResultados);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 340, 210));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(33, 48, 71));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 100, 30));

        btnTablas.setBackground(new java.awt.Color(204, 204, 204));
        btnTablas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnTablas.setForeground(new java.awt.Color(33, 48, 71));
        btnTablas.setText("PLAY");
        btnTablas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnTablas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablasActionPerformed(evt);
            }
        });
        add(btnTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, 30));

        tblDatos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        tblDatos.setForeground(new java.awt.Color(33, 48, 71));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 730, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipo1ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
                                     
     try {
        DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
        int filas = modelo.getRowCount();
        int columnasTot = modelo.getColumnCount();

        if (columnasTot <= 1 || filas == 0) {
            JOptionPane.showMessageDialog(this, "No hay datos para procesar.");
            return;
        }

        int columnas = columnasTot - 1;
        double[][] matriz = new double[filas][columnas];
        double[][] original = new double[filas][columnas];

        // Leer datos de la tabla
        for (int i = 0; i < filas; i++) {
            for (int j = 1; j <= columnas; j++) {
                Object val = modelo.getValueAt(i, j);
                if (val == null || val.toString().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Hay celdas vacías en la matriz.");
                    return;
                }
                double num = Double.parseDouble(val.toString());
                matriz[i][j - 1] = num;
                original[i][j - 1] = num;
            }
        }

        // 🔹 Copia local de nombres de columnas y filas
        String[] columnasNombres = new String[columnas];
        for (int j = 0; j < columnas; j++) {
            columnasNombres[j] = modelo.getColumnName(j + 1);
        }

        // =====================================================
        // 1️⃣ Reducción por filas
        // =====================================================
        for (int i = 0; i < filas; i++) {
            double min = Arrays.stream(matriz[i]).min().orElse(0);
            for (int j = 0; j < columnas; j++) matriz[i][j] -= min;
        }

        // =====================================================
        // 2️⃣ Reducción por columnas
        // =====================================================
        for (int j = 0; j < columnas; j++) {
            double min = Double.MAX_VALUE;
            for (int i = 0; i < filas; i++) min = Math.min(min, matriz[i][j]);
            if (min == Double.MAX_VALUE) min = 0;
            for (int i = 0; i < filas; i++) matriz[i][j] -= min;
        }

        // =====================================================
        // 3️⃣ Asignación con algoritmo Húngaro
        // =====================================================
        int[] asignacion = hungarianAlgorithm(matriz);

        // =====================================================
        // 4️⃣ Mostrar resultado
        // =====================================================
        double total = 0;
        StringBuilder sb = new StringBuilder();
        sb.append("Asignación óptima:\n");

        for (int i = 0; i < filas; i++) {
            int j = asignacion[i];
            if (j >= 0 && j < columnas) {
                double costo = original[i][j];
                total += costo;
                sb.append((i + 1) + "-" + columnasNombres[j] + " = " + costo + "\n");
            }
        }
        sb.append("\nCosto total = ").append(total);

        txtResultados.setText(sb.toString());

    } catch (Exception e) {
        e.printStackTrace();
        txtResultados.setText("Error: " + e.getMessage());
    }
     

    }//GEN-LAST:event_btnCalcularActionPerformed
    
    private void txtColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColumnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColumnasActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
         DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
    modelo.setRowCount(0);
    modelo.setColumnCount(0);
    txtResultados.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablasActionPerformed
       try {
        int filas = Integer.parseInt(txtTipo1.getText());
        int columnas = Integer.parseInt(txtColumnas.getText());

        if (filas <= 0 || columnas <= 0) {
            JOptionPane.showMessageDialog(this, "Debe ingresar valores válidos para filas y columnas.");
            return;
        }

        String[] nombresColumnas = new String[columnas + 1];
        nombresColumnas[0] = "";
        for (int j = 1; j <= columnas; j++) {
            nombresColumnas[j] = String.valueOf((char) ('A' + (j - 1)));
        }

        Object[][] datos = new Object[filas][columnas + 1];
        for (int i = 0; i < filas; i++) {
            datos[i][0] = String.valueOf(i + 1);
        }

        DefaultTableModel modelo = new DefaultTableModel(datos, nombresColumnas) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return col != 0;
            }
        };
        tblDatos.setModel(modelo);
        txtResultados.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese números válidos para filas y columnas.");
    }
    }//GEN-LAST:event_btnTablasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnTablas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    public javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtColumnas;
    public javax.swing.JTextArea txtResultados;
    private javax.swing.JTextField txtTipo1;
    // End of variables declaration//GEN-END:variables
}
