/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author cindy
 */
public class ModeloAsignacion extends javax.swing.JPanel {

    private double[][] valoresOriginales;
    private java.util.List<Integer> columnasColoreadas = new ArrayList<>();
    private java.util.List<Integer> filasColoreadas = new ArrayList<>();
    private int contadorAsignaciones = 0;

    public ModeloAsignacion() {
        initComponents();
    }

//    private double parseNumero(Object valor) {
//        if (valor == null) {
//            return 0;
//        }
//        String texto = valor.toString().trim();
//        if (texto.isEmpty()) {
//            return 0;
//        }
//        try {
//            return Double.parseDouble(texto.replace(",", ".")); // soporta 0,12 o 0.12
//        } catch (NumberFormatException e) {
//            return 0;
//        }
//    }

//    private double getValorNumerico(Object valorCelda) {
//        if (valorCelda == null) {
//            return 0.0;
//        }
//
//        String valorStr = valorCelda.toString().trim();
//        if (valorStr.isEmpty()) {
//            return 0.0;
//        }
//
//        // Permitir comas decimales
//        valorStr = valorStr.replace(",", ".");
//
//        try {
//            return Double.parseDouble(valorStr);
//        } catch (NumberFormatException e) {
//            return 0.0;
//        }
//    }

    private double getValorNumerico(Object valorCelda) {
    if (valorCelda == null) return 0.0;

    String valorStr = valorCelda.toString().trim();
    if (valorStr.isEmpty()) return 0.0;

    valorStr = valorStr.replace(",", "."); // Permitir comas decimales

    try {
        return Double.parseDouble(valorStr);
    } catch (NumberFormatException e) {
        return 0.0;
    }
}

//    private void pintarCeldas() {
//        DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
//        int filas = modelo.getRowCount();
//        int columnas = modelo.getColumnCount();
//
//        boolean[] filasPintadas = new boolean[filas];
//        boolean[] columnasPintadas = new boolean[columnas];
//
//         Detercar filas a pintar
//        for (int i = 0; i < filas; i++) {
//            int cerosFila = 0;
//            for (int j = 1; j < columnas; j++) {
//                if (Math.abs(getValorNumerico(modelo.getValueAt(i, j))) < 0.000001) {
//                    cerosFila++;
//                }
//            }
//            if (cerosFila >= 2) {
//                filasPintadas[i] = true;
//            }
//        }
//
//         Detectar columnas a pintar
//        for (int j = 1; j < columnas; j++) {
//            int cerosCol = 0;
//            for (int i = 0; i < filas; i++) {
//                if (Math.abs(getValorNumerico(modelo.getValueAt(i, j))) < 0.000001) {
//                    cerosCol++;
//                }
//            }
//            if (cerosCol >= 2) {
//                columnasPintadas[j] = true;
//            }
//        }
//         Aplicar TableCellRenderer personalizado
//        tblDatos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
//            @Override
//            public Component getTableCellRendererComponent(JTable table, Object value,
//                    boolean isSelected, boolean hasFocus, int row, int column) {
//                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
//
//                if (column == 0) {
//                    c.setBackground(Color.WHITE);
//                } else if (filasPintadas[row] || columnasPintadas[column]) {
//                    c.setBackground(new Color(173, 216, 230));
//                } else {
//                    c.setBackground(Color.WHITE);
//                }
//                setHorizontalAlignment(SwingConstants.CENTER);
//                return c;
//            }
//        });
//        tblDatos.repaint();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        txtTipo1 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtColumnas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnTablas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setBackground(new java.awt.Color(230, 230, 230));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator1.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator1.setOpaque(true);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 980, 2));

        jSeparator3.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator3.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator3.setOpaque(true);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, -7, 2, 700));

        jSeparator2.setBackground(new java.awt.Color(33, 48, 71));
        jSeparator2.setForeground(new java.awt.Color(33, 48, 71));
        jSeparator2.setOpaque(true);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 663, 980, 2));

        jLabel7.setBackground(new java.awt.Color(230, 230, 230));
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 485, 150, 40));

        jLabel6.setBackground(new java.awt.Color(230, 230, 230));
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 520, 30, 160));

        jLabel5.setBackground(new java.awt.Color(230, 230, 230));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 30, 160));

        jLabel3.setBackground(new java.awt.Color(230, 230, 230));
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 650, 150, 40));

        jTextPane1.setBackground(new java.awt.Color(230, 230, 230));
        jTextPane1.setText("⠐⣪⡑⣤⣶⣶⣶⣦⡔⣩⡒⠀ ⢸⣯⣾⣿⢏⣿⣏⢿⣿⣮⣿⠀ ⢸⣿⢸⡗⣶⠙⢱⡖⣿⢸⣿⠀ ⢸⡿⠀⠳⣄⣐⣂⡴⠃⠸⣿⠀ ⣾⠃⠀⡵⡔⠕⠕⡰⡅⠀⢻⡆ ⢹⡆⠘⢴⠙⠑⠉⢳⡱⠀⣾⠁ ⠊⠀⠀⠈⡖⡖⡖⡎⠀⠀⠈⠂ ⠀⠀⠀⠀⠉⠁⠉⠁⠀⠀⠀⠀");
        jTextPane1.setToolTipText("");
        jScrollPane2.setViewportView(jTextPane1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 130, 140));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 48, 71));
        jLabel2.setText("MODELO de ASIGNACIÓN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 75, -1, 30));

        txtTipo1.setBackground(new java.awt.Color(230, 230, 230));
        txtTipo1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        txtTipo1.setForeground(new java.awt.Color(33, 48, 71));
        txtTipo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTipo1.setBorder(null);
        txtTipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipo1ActionPerformed(evt);
            }
        });
        add(txtTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 370, 25));

        btnCalcular.setBackground(new java.awt.Color(204, 204, 204));
        btnCalcular.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(33, 48, 71));
        btnCalcular.setText("CALCULAR");
        btnCalcular.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 100, 30));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 48, 71));
        jLabel17.setText("Columnas:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 150, 120, 30));

        txtColumnas.setBackground(new java.awt.Color(204, 204, 204));
        txtColumnas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        txtColumnas.setForeground(new java.awt.Color(33, 48, 71));
        txtColumnas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtColumnas.setBorder(null);
        txtColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColumnasActionPerformed(evt);
            }
        });
        add(txtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 155, 120, 25));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 48, 71));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Resultados");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 100, -1));

        txtResultados.setColumns(20);
        txtResultados.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txtResultados.setRows(5);
        jScrollPane3.setViewportView(txtResultados);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 340, 210));

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(33, 48, 71));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 100, 30));

        btnTablas.setBackground(new java.awt.Color(204, 204, 204));
        btnTablas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        btnTablas.setForeground(new java.awt.Color(33, 48, 71));
        btnTablas.setText("PLAY");
        btnTablas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(33, 48, 71), null));
        btnTablas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablasActionPerformed(evt);
            }
        });
        add(btnTablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, 30));

        tblDatos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        tblDatos.setForeground(new java.awt.Color(33, 48, 71));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 730, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipo1ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        try {
            DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
            int filas = modelo.getRowCount();
            int columnas = modelo.getColumnCount();

            if (columnas <= 1 || filas == 0) {
                JOptionPane.showMessageDialog(this, "No hay datos para procesar.");
                return;
            }

            // 🔹 Clonar el modelo original para conservar los valores iniciales
            DefaultTableModel modeloInicial = new DefaultTableModel();
            for (int j = 0; j < columnas; j++) {
                modeloInicial.addColumn(modelo.getColumnName(j));
            }
            for (int i = 0; i < filas; i++) {
                Object[] fila = new Object[columnas];
                for (int j = 0; j < columnas; j++) {
                    fila[j] = modelo.getValueAt(i, j);
                }
                modeloInicial.addRow(fila);
            }

            // ================================
            // 1️⃣ RESTA HORIZONTAL (por fila)
            // ================================
            for (int i = 0; i < filas; i++) {
                double min = Double.MAX_VALUE;
                for (int j = 1; j < columnas; j++) {
                    double num = getValorNumerico(modelo.getValueAt(i, j));
                    if (num < min) {
                        min = num;
                    }
                }
                for (int j = 1; j < columnas; j++) {
                    double num = getValorNumerico(modelo.getValueAt(i, j));
                    modelo.setValueAt(String.format("%.2f", num - min), i, j);
                }
            }

            // ================================
            // 2️⃣ RESTA VERTICAL (por columna)
            // ================================
            for (int j = 1; j < columnas; j++) {
                double min = Double.MAX_VALUE;
                for (int i = 0; i < filas; i++) {
                    double num = getValorNumerico(modelo.getValueAt(i, j));
                    if (num < min) {
                        min = num;
                    }
                }
                for (int i = 0; i < filas; i++) {
                    double num = getValorNumerico(modelo.getValueAt(i, j));
                    modelo.setValueAt(String.format("%.2f", num - min), i, j);
                }
            }

            // ================================
            // 3️⃣ DETECCIÓN DE CEROS VÁLIDOS
            // ================================
            StringBuilder resultado = new StringBuilder();
            for (int i = 0; i < filas; i++) {
                for (int j = 1; j < columnas; j++) {
                    double valor = getValorNumerico(modelo.getValueAt(i, j));

                    if (Math.abs(valor) < 0.000001) { // Es un cero
                        // Verificar si NO hay otro cero debajo
                        boolean tieneDebajo = false;
                        for (int k = i + 1; k < filas; k++) {
                            double valorDebajo = getValorNumerico(modelo.getValueAt(k, j));
                            if (Math.abs(valorDebajo) < 0.000001) {
                                tieneDebajo = true;
                                break;
                            }
                        }

                        if (!tieneDebajo) {
                            double valorInicial = getValorNumerico(modeloInicial.getValueAt(i, j));
                            String nombreColumna = modelo.getColumnName(j);
                            int numeroFila = i + 1;

                            resultado.append("R").append(numeroFila)
                                    .append(" - ").append(nombreColumna)
                                    .append(" - ").append(String.format("%.2f", valorInicial))
                                    .append("\n");
                        }
                    }
                }
            }

            // Mostrar resultado
            txtResultados.setText(resultado.toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar los datos: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColumnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColumnasActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed


    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablasActionPerformed
        try {
            int n = Integer.parseInt(txtColumnas.getText().trim());

            if (n <= 0) {
                JOptionPane.showMessageDialog(this, "Ingrese un número mayor que 0.");
                return;
            }

            // Crear encabezados 
            String[] columnas = new String[n + 1];
            columnas[0] = " ";
            for (int i = 1; i <= n; i++) {
                columnas[i] = String.valueOf((char) ('A' + (i - 1)));
            }

            // Crear datos 
            Object[][] datos = new Object[n][n + 1];
            for (int fila = 0; fila < n; fila++) {
                datos[fila][0] = fila + 1;
                for (int col = 1; col <= n; col++) {
                    datos[fila][col] = "";
                }
            }

            DefaultTableModel modelo = new DefaultTableModel(datos, columnas);
            tblDatos.setModel(modelo);

            JTableHeader header = tblDatos.getTableHeader();
            ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            for (int i = 0; i < tblDatos.getColumnCount(); i++) {
                tblDatos.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número válido en columnas");
        }
    }//GEN-LAST:event_btnTablasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnTablas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane jTextPane1;
    public javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtColumnas;
    public javax.swing.JTextArea txtResultados;
    private javax.swing.JTextField txtTipo1;
    // End of variables declaration//GEN-END:variables
}
